test_dat:
  name: HumaniseMotion
  limit_size: 1
  split: test
  scene_id: "scene0603_00"  #scene0633_01 #scene0603_00 #scene0600_00 Change this to your desired scene ID

dat_cfg:
  humanise_root: data/HUMANISE
  scannet_root: data/ScanNet/
  humanise_prep_root: data/humanise_preprocess
  scannet_prep_root: data/scannet_preprocess
  action: all
  coord: oc
  sample_data_interval: 1
