train_dat:
  name: HumaniseMotion
  limit_size: -1
  split: train

val_dat:
  name: HumaniseMotion
  limit_size: -1
  split: test

test_dat:
  name: HumaniseMotion
  limit_size: 1
  split: test
  scene_id: "scene0600_00" 
  #scene0663_00
  #scene0677_00
  #scene0685_00
  #scene0692_00
  #scene0694_00
  #scene0703_00 #scene0600_00 


dat_cfg:
  humanise_root: data/HUMANISE
  scannet_root: data/ScanNet/
  humanise_prep_root: data/humanise_preprocess
  scannet_prep_root: data/scannet_preprocess
  action: all
  coord: oc
  sample_data_interval: 1