# EchoMotionAI Configuration File
# Contains all static configurations, API keys, and endpoints

# Azure OpenAI Configuration
azure_openai:
  api_key: ""  # Consider moving to environment variable
  endpoint: ""
  api_version: ""
  deployment: ""
  model_name: ""
  model_settings:
    max_tokens: 300  # Default max tokens for general use
    generation_tokens: 10  # Specific for dataset generation

# Azure Speech Service Configuration
azure_speech:
  subscription_id: ""
  region: ""  # Default region, adjust if needed
  language: "en-US"
  output_format: "detailed"

# MongoDB Atlas Configuration
mongodb:
  connection_string: "mongodb+srv://url/?retryWrites=true&w=majority&appName=echomotion"
  database_name: "echomotion"
  collections:
    conversations: "conversations"
    agents: "agents"
    scenes: "scenes"
  retention_period_days: 30  # How long to keep conversation history

# Model Parameters
model:
  clip:
    enabled: true
    device: "cuda"  # Default device for CLIP model

# Paths and Directories
paths:
  data_dir: "data"
  output_dir: "outputs"
  model_dir: "models"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Visualization Configuration
visualization:
  vis_dir: "out/vis3d"
  host: "localhost"  # Default host, can be overridden by environment variable
  port: 8080  # Default port, can be overridden by environment variable
  save_path: "out/test/generate_most_twostage_motion_all/sample.pkl"

# Agent Configuration
agent:
  prompt_type: "paper"
  checkpoint_dir: "agent_checkpoints"
  memory_enabled: true

# Note: It's recommended to move sensitive information like API keys to environment 
# variables in production environments for better security.

HUGGINGFACE_TOKEN: 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

LLM_BASE_URL : "http://localhost:8005"
